[build]
  # Build command for Flutter web - all on one line
  command = "echo 'Starting Flutter web build...' && git clone https://github.com/flutter/flutter.git -b stable --depth 1 flutter && export PATH=\"$PWD/flutter/bin:$PATH\" && flutter doctor -v && flutter config --enable-web && flutter pub get && flutter build web --release --no-tree-shake-icons --base-href /"
  
  # Directory containing the built files
  publish = "build/web"
  
  # Skip dependency installation phase
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  # Flutter installation
  FLUTTER_VERSION = "3.5.0"
  NODE_VERSION = "18"
  
  # Skip Ruby/Python dependency checks
  NETLIFY_USE_YARN = "false"
  
  # Flutter storage optimization
  PUB_CACHE = "/opt/build/cache/.pub-cache"

# Handle SPA routing - CRITICAL for Flutter web
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy (if needed in future)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend.com/api/:splat"
  status = 200
  force = true

# Headers for performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Compression for JS files
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Encoding = "gzip"

# Build processing optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  minify = true

[build.processing.js]
  minify = true

[build.processing.html]
  minify = true

[build.processing.images]
  compress = true