[build]
  command = "mkdir -p /opt/buildhome/flutter && cd /opt/buildhome && git clone https://github.com/flutter/flutter.git -b stable --depth 1 && export PATH=\"$PATH:/opt/buildhome/flutter/bin\" && cd $NETLIFY_BUILD_BASE && flutter doctor && flutter pub get && flutter build web --release"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.19.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  FLUTTER_VERSION = "3.19.0"

[build.processing]
  skip_processing = false

[build.processing.css]
  minify = true

[build.processing.js]
  minify = true

[build.processing.html]
  minify = true

[build.processing.images]
  compress = true